spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6002 # 服务端口
spring:
  profiles: dev # 生产环境 application:
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: server2 # eureka服务端的实例名称
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://server1:6001/eureka/
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: 6002 # 服务端口
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: server2 # eureka服务端的实例名称
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://server1:6001/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true # 开启自我保护机制*****************